//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelSCSDB : DbContext
    {
        public ModelSCSDB()
            : base("name=ModelSCSDB")
        {
            foreach (Device device in Device)
            {
                device.SetNavProps();
            }
            foreach (Orders orders in Orders)
            {
                orders.SetNavProps();
            }
            foreach (ServiceOrder serviceOrder in ServiceOrder)
            {
                serviceOrder.SetNavProps();
            }
            foreach (SpareOrder spareOrder in SpareOrder)
            {
                spareOrder.SetNavProps();
            }
            foreach (Task task in Task)
            {
                task.SetNavProps();
            }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client Client { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceOrder> ServiceOrder { get; set; }
        public virtual DbSet<Spare> Spare { get; set; }
        public virtual DbSet<SpareOrder> SpareOrder { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
