//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ServiceOrder = new HashSet<ServiceOrder>();
            this.SpareOrder = new HashSet<SpareOrder>();
        }
    
        public int ID { get; set; }
        public int DeviceID { get; set; }
        public int ManagerID { get; set; }
        public int MasterID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double Price { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Master Master { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpareOrder> SpareOrder { get; set; }

        public void SetNavProps()
        {
            Device = Device;
            Manager = Manager;
            Master = Master;
            Status = Status;
        }
    }
}
