//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrder
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int OrderID { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Service Service { get; set; }

        public void SetNavProps()
        {
            Orders = Orders;
            Service = Service;
        }
    }
}
