//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public int ManagerID { get; set; }
        public int MasterID { get; set; }
        public int StatusID { get; set; }
        public string TaskText { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Master Master { get; set; }
        public virtual Status Status { get; set; }

        public void SetNavProps()
        {
            Manager = Manager;
            Master = Master;
            Status = Status;
        }

        public override string ToString()
        {
            return $"{TaskText}";
        }
    }
}
